server:
  port: 5000
spring:
  application:
    name: atguigu-crowd-project
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.85.128
    password: 123456
    session:
      store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
aliyun:
  oss:
    access-key-id: LTAI4G7Lo6hSNkyetM5iNbWZ
    access-key-secret: QvevGmPL7hy1OsHkSdMKltaQIHS1W2
    bucket-domain: http://jie123456.oss-cn-shenzhen.aliyuncs.com
    bucket-name: jie123456
    end-point: http://oss-cn-shenzhen.aliyuncs.com
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
