server:
  port: 4000
spring:
  application:
    name: atguigu-crowd-auth
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.85.128
    password: 123456
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
mybatis:
  mapper-locations: classpath*:/mybatis/mapper/*Mapper.xml
short:
  message:
    app-code: 8845c99cd0bc4597bdbd4282a110ef3b
    host: https://feginesms.market.alicloudapi.com
    method: GET
    path: /codeNotice
    sign: 151003
    skin: 84683
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000